//! Bindgen-generated KFD ioctl bindings.
//!
//! Generated by `build.rs` from the vendored `include/kfd_ioctl.h` on every
//! host, so the module compiles unconditionally (AMD codepaths fail with
//! `Error::NoAmdGpu` at runtime where there is no GPU).

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    unsafe_op_in_unsafe_fn,
    clippy::missing_safety_doc
)]

include!(concat!(env!("OUT_DIR"), "/kfd_sys.rs"));
