//! ONNX protobuf types generated by prost.
//!
//! These types are generated from `onnx.proto` at compile time.

pub mod onnx {
    #![allow(clippy::doc_overindented_list_items)]
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

pub use onnx::*;
