//! ONNX protobuf types generated by prost.
//!
//! These types are generated from `onnx.proto` at compile time.

pub mod onnx {
    include!(concat!(env!("OUT_DIR"), "/onnx.rs"));
}

pub use onnx::*;
